### ISSUE TITLE
Faculty profile page..

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#27]
Add a page for faculty to show their bio.. 
At least, department...

**Comment by vinkumbr** [comment]
Options for changing password needs to be provided for the faculty in the profile tab.

**Comment by nihesh7391** [comment]
Added faculty profile page..
It displays their Name and Department
Now, faculty can change the password...

**Comment by s-gv** [comment]
I'm re-opening this because of inconsistencies and bugs in the faculty view.
- The profile page link disappears when the faculty navigates to the FAQ page.
- The top nav bar in the faculty FAQ page says "Home", but it should be showing "Advisees" and "Courses". The same issue is present when the faculty is seeing the courses taken by a student and when viewing course applicants. I think "courses" and "advisees" should be rendered in separate views like '/faculty/courses' and '/faculty/advisees'. 
- In the course page for faculty to approve students, the email address at the right top disappears, and hitting on the profile page under the nameless dropdown menu triggers a server error.

**Comment by nihesh7391** [comment]
All the above issues are fixed with current push!!
