### ISSUE TITLE
Allow students and faculty to undo actions where possible

### ISSUE THREAD

**Issue by s-gv** [s-gv/bheemboy#45]
A confirmation dialog would be nice for actions such as "Drop request" that are difficult to reverse. Also, how about hiding actions like "Drop", "Credit to Audit" by default and showing them only when the student clicks on the course?

**Comment by s-gv** [comment]
On second thought, a better design would allow the user to undo actions. For example, having a "Cancel drop request" action appear if the advisor is yet to approve the drop is better than a dialog box saying "Warning: Are you sure you want to drop the course? This action can't be easily undone".

**Comment by s-gv** [comment]
Note that this applies to instructors and advisors too. An instructor shouldn't have to meet the admin because he accidentally rejected a student's request.

**Comment by arthi-ramaniam** [comment]
Not adding Undo option because it is too complex to implement. We need to introduce a n-1 state , trace it back. 

As of now, for advisor and instructor, for reject options, added an alert for confirmation. <Unable to make cancel as default>
For student, attempt to cancel. Unable to add confirm boxes here. For students, there is a choice of "Revert" for A/C/D. 
Meet DCC - Confirm box is not needed , I suppose.
