### ISSUE TITLE
Cancel a course registration at any time prior to DCC approval

### ISSUE THREAD

**Issue by rajeshsundaresan** [s-gv/bheemboy#49]
A student should be able to cancel a course registration at any time prior to DCC approval. Advisor to approve the cancellation. Instructor need not be informed of the cancellation. Just remove the student name from the list of enrolled students.

**Comment by nihesh7391** [comment]
Implemented the feature!!

**Comment by bhargavajs07** [comment]
If advisor rejects cancellation of a course enrolment prior to DCC approval, shouldn't it be treated as an active request (ie., revert it back to INSTRUCTOR_APPROVED state in participant table) ?  

Currently, a new state (Advisor rejected cancellation) is added to the participant table to for this scenario, I feel its not right way to model it. 

Due to this, if advisor rejects cancellation, on DCC page this turns up as an inactive request with no action DCC or student or advisor could perform on it.. I think this scenario is better modeled by reverting back to INSTRUCTOR_APPROVED state when advisor rejects cancellation.

**Comment by rajeshsundaresan** [comment]
If advisor rejects cancellation, please revert back to INSTRUCTOR_APPROVED as suggested by Bhargav.

Rajesh

**Comment by nihesh7391** [comment]
Now, a student can cancel a course until DCC approves it.
This means a course can be in two state: Adviser approves or Instructor approves
So, when adviser rejects cancellation request, it should be reverted to its earlier state.
Implemented the same in current push...

**Comment by arthi-ramaniam** [comment]
Also added changes for "Instructor Reject". The way out to clear the entry is - student has to raise the request for cancel. If advisor approves this "Cancel request", entry deleted from table. If advisor rejects this "Cancel Request", the status roles back to "Advisor Approved".  ( This goes as part of cancel_request and not part of cancel_request_1)  @nihesh7391 .

**Comment by arthi-ramaniam** [comment]
"Cancel request" raised by the student after "Instructor Reject" deletes the entry from participant table. No advisor approval required.
