### ISSUE TITLE
Documentation and Testing

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#76]
Comment the code and write a documentation.
Test for faculty and DCC views.

**Comment by bhargavajs07** [comment]
Please re-assign to someone else if they have already started working on it.

**Comment by bhargavajs07** [comment]
Create an architecture diagram and 1 line for each view documentation.

**Comment by s-gv** [comment]
Everyone, complete todos in DOCUMENTATION.md. Announce what part you are going to do in this thread. The screencast can be done after final deployment.

**Comment by vinkumbr** [comment]
With reference to the bheemboy meeting on 07/10/2016, I will write a manual for bheemboy detailing the registration process, course A/C and drop conversions etc. Although this will be specific to our Institute(esp. for handing it over to DIGITS), I will try to keep it general so that it can be incorporated here. It would be great if one of you could take up the schema design.
