### ISSUE TITLE
Add badges

### ISSUE THREAD

**Issue by nihesh7391** [s-gv/bheemboy#79]
Add badges for enhanced functionality in DCC page.
Also remove serial number from DCC page.

**Comment by s-gv** [comment]
An `in-progress` badge has been added next to DCC review pending students. There is a performance issue here.  When the DCC view is opened, a query is made for each active student in the dept. (about 200 queries). That's not great, but each of those queries is for courses taken by a student, which is indexed and will return only about 10-15 rows. Since we're not doing 200 full table scans, it's kind of ok. 

This issue is left open if anyone wants to take a shot at optimizing this by coaxing the Django ORM to issue the right SQL aggregate query.
