### ISSUE TITLE
New alerts

### ISSUE THREAD

**Issue by arthi-ramaniam** [s-gv/bheemboy#98]
![adv_before](https://cloud.githubusercontent.com/assets/19235834/19572479/13c226c8-9720-11e6-86a9-de32b6ae50f2.png)
![adv_after](https://cloud.githubusercontent.com/assets/19235834/19572480/13cbd47a-9720-11e6-96ef-ec22193794fc.png)

In adviser/instructor page, if adviser makes one decision like reject, all new applications, which he has not reviewed also disappear. Its not possible for the adviser/instructor to disambiguate the new issues from old ones.

**Comment by s-gv** [comment]
Isn't this the desired behaviour? In the manual mode, the "new" badge remains until the faculty hits the review button, and in the auto mode, the badge goes away after the faculty has seen changes to the course list once.

**Comment by arthi-ramaniam** [comment]
Added Approve option in both instructor and adviser.

**Comment by rajeshsundaresan** [comment]
No it is not. Imagine this situation.

Adviser sees 6 "new" items for a student. Adviser starts to review one 
by one. First course OK. Second course Reject. Call from Chairman since 
an international delegation has arrived. Once back 7th year student 
walks in with his sloppily written thesis. After sending him on his way, 
Adviser goes back to the student's registration page, and refreshes. 
 From where should he resume?

The above is not abnormal.

For students, courses loom large. That is all they do in the first 1.5 
years. For advisers, nothing can be farther from courses.

I want the approve button back, or the "new" to be maintained until some 
action by the adviser.

What does 'disable student edits' do?

Thanks,
Rajesh
